TRAIN:
  ENABLE: True
  DATASET: SC3000
  BATCH_SIZE: 3
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  # CHECKPOINT_FILE_PATH: path to the model to test
  CHECKPOINT_TYPE: caffe2
TEST:
  ENABLE: True
  DATASET: SC3000
  BATCH_SIZE: 3
NUM_GPUS: 3
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
DATA:
  PATH_TO_DATA_DIR: /media/data2/sc3000-nostrils-mixed
  NUM_FRAMES: 128   # 32  # num_frames (int): number of frames to sample.
  SAMPLING_RATE: 3  # 5 frames / s
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
  TARGET_FPS: 30
SLOWFAST:
  ALPHA: 4
  BETA_INV: 16
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 9
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_STRIDES: [[1, 1], [1, 1], [1, 1], [1, 1]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.00001 # 0.0001
  LR_POLICY: cosine
  MAX_EPOCH: 1000
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 50.0
  WARMUP_START_LR: 0.0001
  OPTIMIZING_METHOD: adam
MODEL:
  HEAD_ACT: none
  NUM_CLASSES: 1
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: mse
  DROPOUT_RATE: 0.7
